# Generated by Django 5.2.1 on 2025-05-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BirthdayForm',
            new_name='Birthday',
        ),
    ]
