# Generated by Django 5.2.1 on 2025-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_tag_birthday_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'тэги'},
        ),
    ]
